[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/17ihEevHcYY3joMBGqT4T_MdxXVhfVkvk-Otp1M24RkU/edit"

type = "service_account"
project_id = "klocdata"
private_key_id = "ce7e1565a82796370ae860a1292a24823829b0b0"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9S4JpWLa57WVR
/j4jTQ3T/2q9Qgx9Jw8RXtCWGc1zMd2q+cuHjTY2DSyWKzUk5EQYM4VV7Ps4FKDw
yGvWzTcqzBK6a75G+n6dcVojGMTu3WNDJhdYqelpTvuBXlLHfFEs1yVNudpahW1j
HiTtAH3qY0dl3bAU27y+j9iHVODfdm7F7b113V3uw5S8cp0HxXLq6poI2HqtBxCz
HCtNihd2UhPj1kZMjc79vcFXJWRP5OBgp3u9zPDYi4zRx0BY1sXUh7iEOiW2po7Q
LmAq6RCr5U35vO3m6w8Eowely2s3Pw+oc/6CcTufzGJoQWEarSESJ3ylnwvYVdd8
dSz3fHrZAgMBAAECggEAE37qJsrwANyyHXx7rluSg8XP2r+pdR9XdjDHd1ofdpCJ
dcFF5MdWsMDxGWNIVS0cVUjDIAspAYjgXYQq1SPsHWCIwkH0Bi/o5/LDd49mwvoy
rbkH2QYg58tubE/IY0rKun1LFoMAeee5kSaK44z0KvaAJT3sk21hNlgu0xtbELCe
fGhSzSYj0hdj23enlw46X5nuvjj+wYzyVdLqGvBHMiiekQJcUwHT9pDy2l8C8xmj
Csvh0olToXRCRcowH0TdEH/hB9npfWIB75D/Ossvm1l+C1ZVXmc46xOmktfr4orC
0EhvU5ZpNrq4PtCsWPoDhtCPYFmYZmC/mIBqmYWEIQKBgQD5SUwiWjVD5vwIqyZo
6TOZ+DrtAoCG/WiKpuanUlM4VX67LLYZ4w2zyvfN54jIqLaS4lZsE8GV1N1Swaux
tLmOAxx5xi/iNIQQyq+hTFcI2HXnhJQGgnigo7VFCmQjPE4jKNBuZncLI1fl2RN1
ADHdUr/PubIO1p5cAMhWQKNmqQKBgQDCZJogVC4Zn5XJ1m8aoj3Iwm5aGasBC09z
EHT4fXrtVZvD1hFSX3Z+J53RQFcpD5UBKGBNsCBEH8KuFK3sDsabmb5mTSHyJJ2S
xj6NRLZBQ/ik8J4tRiO9HSjTiEddu6KGJmfLdvcnPG0+T0s74yt0t+bM9s/cMOvQ
R3VPLH6AsQKBgFoxyvoi6WLIECiSxDLxLVpoFenrHdW5mjmQaaPghXu8cz4Fz11O
aYbDySUWwMbZRDWg7uPrwf8UJX/r0tNZMEnRllv4+Ro/JgltTF5v4I2yw/YgYe55
BmwYz11LhS+6ggr2mXNYX3oIL6VaBVAv4drSNdRSu7nirSlcnx+WA4kBAoGAHml4
x2gEElQqLfqTRTpuqhLpCsWLQE2Rr3G6qwmOisTi6p959EYlFpWCFjOXrz/V0umL
L3xHgADsByoLD6w8HCnQZNbaYbSixkynipheXxWQN9XBGVooyzRdp8JhT+PECHLH
uEgzYHsOqDnljkf7C3ad8CEI4ezxZ5NWYf2XCPECgYEAh7m/WUs8MuH5bWOYUnGv
5SNLlab/1bMiSn+A9Kw1DqjZMI7eFa6LQBFyQdvUcM2sz6P1/E713rFrOMuPy3z9
LPXXlzDUGr4etTfPsHW82qOHW05UiVbwq1qLtCjYW5h3Vxs78UmJhUVDnnE0Zl+d
RZ6EIrJf/bN3UWskgfF3HfI=
-----END PRIVATE KEY-----"""
client_email = "aazaad@klocdata.iam.gserviceaccount.com"
client_id = "116191767934428191603"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/aazaad%40klocdata.iam.gserviceaccount.com"
universe_domain = "googleapis.com"